### ISSUE TITLE
Example PostgreSQL

### ISSUE THREAD

**Issue by bendo01** [techknowlogick/go-oauth2-gorm#1]
is there any example using postgresql?

**Comment by techknowlogick** [comment]
Hi @bendo01 Thanks for the Question.

To create a store with postgres, you'll need to pass the connection information such as
```go
storeConfig := NewConfig("postgres", "host=myhost port=myport user=oauth2 dbname=oauth2 password=mypassword", "")
store := NewStore(storeConfig, 600)
```
I am going to close this ticket now, but please feel free to ask more questions 😄
