### ISSUE TITLE
Expired token deletion

### ISSUE THREAD

**Issue by michel-foucault** [techknowlogick/go-oauth2-gorm#3]
Reviewing your code before using it I am wondering why you changed the expired_at condition for token counting and deletion.

In the code from `go-oauth2/mysql` the condition is:
[expired_at<=?](https://github.com/go-oauth2/mysql/blob/f1cfb78d2949aba7fc68c20cf9cf32e5ba60628f/mysql.go#L130
)

your condition is:
[expired_at > ?](https://github.com/techknowlogick/go-oauth2-gorm/blob/a561e9f2b1cf5ef4cff6b39a8a6c5cbf04a6f40b/gorm.go#L113)

For me the first is the good one.
Add an unit test for this should be great

**Comment by DogBaoBao** [comment]
> expired_at<=?

Hi, I have update this go-oauth2-gorm to gorm v2 and use  `expired_at<=?` like `go-oauth2/mysql` in https://github.com/DogBaoBao/go-oauth2-gorm

**Comment by techknowlogick** [comment]
@DogBaoBao could you send a PR?

**Comment by DogBaoBao** [comment]
> @DogBaoBao could you send a PR?

I directly send a PR to your master?
